### ISSUE TITLE
>>can take layout and diff calculation to non-main thread

### ISSUE THREAD

**Issue by viktor-malieichyk** [BohdanOrlov/ios-skills-matrix#5]
Diff calculation, sure. But layout in background, really? Technically you can do that, but ios autolayout engine is not supposed to work on background thread. Or you just wanted to say that senior developer should be able to write his own thread-safe autloayout engine? :)

**Comment by BohdanOrlov** [comment]
Hey, @viktor-malieichyk believe me or not but people do make manual frame calculation in background thread and don't use autolayout. 

This is just inevitable in performance critical places like chat in which user should be able to scrolling dozens of messages per second without a single FPS drop.

Can it work with autolayout? Sure it can, but good like trying to get stable 60 FPS ;)

**Comment by viktor-malieichyk** [comment]
Oh, so that is what you meant, ok then.
