### ISSUE TITLE
Hey look there is a question on StackOverflow about this very repository!

### ISSUE THREAD

**Issue by isaac-weisberg** [BohdanOrlov/ios-skills-matrix#6]
https://stackoverflow.com/questions/52372423/why-does-usage-of-structs-increase-applications-binary-size

Spoiler: the question is by me and I have been wondering about it ever since seeing it for the first time somewhere in April.

**Comment by BohdanOrlov** [comment]
@isaac-weisberg I've also replied there, thanks.
